version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      prod:
        dependency-type: "production"
      dev:
        dependency-type: "development"
    ignore:
      - dependency-name: "@nx*"
      - dependency-name: "nx"
      - dependency-name: "*angular*"
      - dependency-name: "typescript"
      - dependency-name: "*eslint*"
      - dependency-name: "*prettier*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
